// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCNL2dySTbWcLMh7fq8EeR6q2K2chn46s',
    appId: '1:405767780725:web:a918f35f9aaae8d950fb3c',
    messagingSenderId: '405767780725',
    projectId: 'chat-app-d415c',
    authDomain: 'chat-app-d415c.firebaseapp.com',
    storageBucket: 'chat-app-d415c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3IIc1ZM5ZvZ1lSZKi1UFIEuF-nsy74kI',
    appId: '1:405767780725:android:26618baf19042fd250fb3c',
    messagingSenderId: '405767780725',
    projectId: 'chat-app-d415c',
    storageBucket: 'chat-app-d415c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8BXzOJcXO2bCzv44paIu8T02XUVLA7BE',
    appId: '1:405767780725:ios:76fc71fbe1a66c5350fb3c',
    messagingSenderId: '405767780725',
    projectId: 'chat-app-d415c',
    storageBucket: 'chat-app-d415c.appspot.com',
    iosBundleId: 'com.example.chatMessengerApp',
  );
}
